### PR TITLE
added tutorial for creation and execution of recordings bulk actions job

### PR DESCRIPTION
**Pull request by Ilan-2019**

### CODE REVIEW

**Comment by PrinceNebulon** [comment]
Thanks for the contribution! I just merged a set of tutorials for bulk recording exports that's been in PR for a while. It has tutorials for Java, .NET, and node.js. Could you update your python tutorial to be part of the [recordings-downloader tutorial](https://github.com/MyPureCloud/developercenter-tutorials/tree/master/recordings-downloader)? Your code doesn't need to be written exactly the same as the rest, but should work with the existing descriptions for the tutorial.

**Comment by Ilan-2019** [comment]
> Thanks for the contribution! I just merged a set of tutorials for bulk recording exports that's been in PR for a while. It has tutorials for Java, .NET, and node.js. Could you update your python tutorial to be part of the [recordings-downloader tutorial](https://github.com/MyPureCloud/developercenter-tutorials/tree/master/recordings-downloader)? Your code doesn't need to be written exactly the same as the rest, but should work with the existing descriptions for the tutorial.

it's not the exact same feature as the tutorials for that's been merged, making it under recordings-downloader will cause for a confusion

**Comment by PrinceNebulon** [comment]
It would be nice if they could be worked together, but I see that this one is using a slightly different approach to retrieving the recordings.

**Comment by PrinceNebulon** [comment]
Need to use the sdk auth method before this can be merged.

**Comment by Ilan-2019** [comment]
> Need to use the sdk auth method before this can be merged.

What is the ask auth method? I am already using auth method of the sdk

**Pull request merged**
