### PR TITLE
Add agent chat assistant tutorial

### PR DESCRIPTION
**Pull request by AgnesCorpuz**

### CODE REVIEW

**Comment by PrinceNebulon** [comment]
Thanks for adding this! I didn't get a chance to fully review it yet, but should get to it tomorrow. Is this essentially an implementation of the agent chat APIs and response management? Any other functionality that I should be aware of?

**Comment by AgnesCorpuz** [comment]
Yes, the main functionality of this tutorial is to send a suggested message by the logged in agent. The tutorial actively listens to the chat interaction and "watch out" for keywords to give a suggestion. Other than that, no other functionalities.

**Comment by PrinceNebulon** [comment]
I ran the app using a local web server in the `javascript` directory and didn't modify anything. The app initializes, but it starts throwing errors when a new chat comes in. I'm creating a chat via the dev tools.

image

**Comment by AgnesCorpuz** [comment]
Hi Tim, thank you for raising the issue. I have fixed the error and pushed to my fork.

**Pull request merged**
